# What is numpy?
* NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

* At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types


## Numpy Arrays Vs Python Sequences
* NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

* The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

* NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

* A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [1]:
# np.array
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
# 2D array
b = np.array([[1, 2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
# 3D Array
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
# dtype
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [7]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [11]:
# With reshape
print(np.arange(1,11).reshape(5, 2))
# np.arange(16).reshape(2,2,2,2)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [12]:
# np.ones and np.zeros
print(np.ones((3,4)))
print(np.zeros((3, 2)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [17]:
# np.random
np.random.random((3,4))

array([[0.17500871, 0.92350067, 0.75491626, 0.65877817],
       [0.63767853, 0.47160298, 0.32499407, 0.19557985],
       [0.55822825, 0.22711304, 0.39144397, 0.04848615]])

In [18]:
# np.linspace(liner space) => lower range, upper range, number of item you want, dtype
# it is generate points in equal distance
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [20]:
# np.identity => create identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Array Attributes

In [21]:
# creating 3 array
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [23]:
# ndim(number of dimenation) =  its give the number of dimention od an array
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [24]:
# shape =>its give the row and column and item of a matric or array
print(a1.shape)
print(a2.shape)
print(a3.shape)


(10,)
(3, 4)
(2, 2, 2)


In [25]:
# size = its give me the number of items 
print(a1.size)
print(a2.size)
print(a3.size)


10
12
8


In [28]:
# itemsize = its tells that how much memory occuipied evey item of array
a3.itemsize

4

In [29]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


### Changing Datatype

In [30]:
# astype = change the datatype of exiting array
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

### Array Operations

In [32]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [33]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [34]:
# relational = comparison with eery item of array
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

### Array Functions

In [38]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[81.,  5., 34.],
       [23., 83.,  2.],
       [26.,  6., 37.]])

In [43]:
# max/min/sum/prod
# 0 -> col and 1 -> row
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
# print(np.prod(a1))
print(np.prod(a1, axis=1))


83.0
2.0
297.0
[13770.  3818.  5772.]


In [46]:
# mean/median/std/var
print(np.mean(a1))
print(np.median(a1, axis=0))
print(np.std(a1))
print(np.var(a1))

33.0
[26.  6. 34.]
28.759539480163987
827.1111111111111


In [47]:
# trigonomoetric functions
np.sin(a1)

array([[-0.62988799, -0.95892427,  0.52908269],
       [-0.8462204 ,  0.96836446,  0.90929743],
       [ 0.76255845, -0.2794155 , -0.64353813]])

In [48]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [49]:
# log and exponents
print(np.log(a1))
print(np.exp(a1))

[[4.39444915 1.60943791 3.52636052]
 [3.13549422 4.41884061 0.69314718]
 [3.25809654 1.79175947 3.61091791]]
[[1.50609731e+35 1.48413159e+02 5.83461743e+14]
 [9.74480345e+09 1.11286375e+36 7.38905610e+00]
 [1.95729609e+11 4.03428793e+02 1.17191424e+16]]


In [52]:
# round/floor/ceil

print(np.round(np.random.random((2,3))*100))
print(np.floor(np.random.random((2,3))*100))
print(np.ceil(np.random.random((2,3))*100))


[[86. 25. 23.]
 [77. 51. 13.]]
[[43. 47. 13.]
 [54. 49. 28.]]
[[19. 86.  6.]
 [51. 17. 49.]]


### Indexing and Slicing

In [53]:
# creating array
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [54]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
a2[1,3]  # row column

7

In [56]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [64]:
a3[1,0,1]

5

In [65]:
a3[1,1,0]

6

In [66]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
a1[2:5:2]

array([2, 4])

In [68]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
a2[:,2]

array([ 2,  6, 10])

In [71]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [69]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

### Iterating

In [73]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [74]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [76]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [77]:
for i in a3:
  print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [78]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7


### Reshaping

In [79]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
# Transpose
np.transpose(a2)
a2.T # another syntax

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [82]:
# ravel - any dimenional array will be converted into 1D array
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

### Stacking

In [83]:
# Creating array
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

print(a4)
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [84]:
# horizontal stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [85]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [86]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
# horizontal splitting

np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [89]:
# vertical splitting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [90]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]